apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sehatq-shop.fullname" . }}
  labels:
    {{- include "sehatq-shop.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/resource-policy: keep
data:
  SECRET_KEY_BASE: {{ .Values.SECRET_KEY_BASE | b64enc }}
