apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sehatq.fullname" . }}
  labels:
    {{- include "sehatq.labels" . | nindent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-weight: "-10"
    helm.sh/resource-policy: keep
data:
  API_URL: {{ .Values.API_URL | quote }}
