apiVersion: kops.k8s.io/v1alpha2
kind: InstanceGroup
metadata:
  creationTimestamp: "2021-11-04T14:14:28Z"
  generation: 1
  labels:
    kops.k8s.io/cluster: k8s.sehatq.com
  name: database
spec:
  cloudLabels:
    k8s.io/cluster-autoscaler/enabled: ""
    k8s.io/cluster-autoscaler/node-template/label: ""
  image: kope.io/k8s-1.15-debian-stretch-amd64-hvm-ebs-2020-11-19
  machineType: m5a.large
  maxSize: 3
  minSize: 3
  nodeLabels:
    kops.k8s.io/instancegroup: database
    on-demand: "true"
  role: Node
  subnets:
  - ap-southeast-1a
  taints:
  - database=true:NoSchedule